export {
	type BrowserBridgeClientOptions,
	type BrowserBridgeState,
	BrowserBridgeUnavailableError,
	type BrowserTabSummary,
	browserClick,
	browserCloseTab,
	browserDoubleClick,
	browserKey,
	browserListTabs,
	browserNavigate,
	browserOpenTab,
	browserScreenshot,
	browserScroll,
	browserType,
	browserWait,
	type ClickInput,
	type CloseTabInput,
	type DoubleClickInput,
	type KeyInput,
	type KeyModifiers,
	type ListTabsInput,
	type ListTabsResult,
	loadBrowserBridgeState,
	type MouseButton,
	type NavigateInput,
	type NavigateResult,
	type OkResult,
	type OpenTabInput,
	type OpenTabResult,
	type ScreenshotInput,
	type ScreenshotResult,
	type ScrollInput,
	type TypeInput,
	type WaitInput,
	type WaitResult,
} from "./client.ts";
export { computeExtensionIdFromKey, type InstallResult, installBrowserBridge } from "./install.ts";
export {
	type BrowserBridgePaths,
	DEFAULT_BROWSER_BRIDGE_PORT,
	type ResolveBrowserBridgePathsOptions,
	resolveBrowserBridgePaths,
	resolveBrowserBridgePort,
} from "./paths.ts";
export { type BrowserBridgeServerOptions, startBrowserBridgeServer } from "./server.ts";
